# Generated by Django 2.2.10 on 2020-03-09 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pid', models.IntegerField()),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=11)),
                ('sex', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('face_url', models.CharField(default='/static/myadmin/img/user05.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tuijian', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('price', models.FloatField()),
                ('num', models.IntegerField(default=10)),
                ('ISBN', models.CharField(max_length=13)),
                ('context', models.TextField()),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Booktype')),
            ],
        ),
        migrations.CreateModel(
            name='BookImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
            ],
        ),
    ]
