# Generated by Django 2.2.10 on 2020-04-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='typeid',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='addtime',
            new_name='Add_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='Pass_word',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='logintime',
            new_name='Save_time',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='sex',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='User_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='face_url',
        ),
        migrations.AddField(
            model_name='users',
            name='Face_url',
            field=models.CharField(default='/static/myadmin/img/user05.png', max_length=180),
        ),
        migrations.DeleteModel(
            name='BookImgs',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Booktype',
        ),
    ]
