# Generated by Django 2.2.10 on 2020-05-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20200419_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=10)),
                ('Book_pid', models.IntegerField()),
                ('Book_path', models.CharField(max_length=50)),
            ],
        ),
    ]
