# Generated by Django 2.2.10 on 2020-06-02 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_booktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Tuijian', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=50)),
                ('Publisher', models.CharField(max_length=100)),
                ('Pub_date', models.DateTimeField()),
                ('Price', models.FloatField()),
                ('Num', models.IntegerField(default=10)),
                ('Isbn', models.CharField(max_length=13)),
                ('Context', models.TextField()),
                ('Type_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.BookType')),
            ],
        ),
        migrations.CreateModel(
            name='BookImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_img_url', models.CharField(max_length=100)),
                ('Book_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Books')),
            ],
        ),
    ]
